config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  post 'posts', to: 'posts#create', as: 'create_post'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    # text, date
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
    # title, content, date
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    # name, email, password
    has_many :posts
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
	  @post = Post.create(post_params)
	 
	  respond_to do |format|
	    if @post.save
	      format.html  { redirect_to(@post,
	                    :notice => 'Post was successfully created.') }
	      format.json  { render :json => @post,
	                    :status => :created, :location => @post }
	    else
	      format.html  { render :action => "new" }
	      format.json  { render :json => @post.errors,
	                    :status => :unprocessable_entity }
	    end
	  end
	end

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])

		respond_to do |format|
		format.html  # show.html.erb
		format.json  { render :json => @post }
  		end
  	end

	def new
		@post = Post.new
	end

	private
	def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimerEjemploRuby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, url: create_post_path(post)) do |f| %>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Listado de posts</h1>
  <ul>
     <% @posts.each do |p| %>
       <li><%= p.title %>, <%= p.date %></li>
     <% end %>
  </ul>
  <%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form', post: @post %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
 
 
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>